#pragma once
enum screen{
    MAINSCREEN,
    ALGORITHM_LIST,
    DATASTRUCTURE_LIST,
    LINEARSEARCH,
    BINARYSEARCH,
    ARRAY_VISUALIZER,
    QUEUE_VISUALIZER,
    BUBBLESORT_VISUALIZER,
    SELECTIONSORT_VISUALIZER,
    STACK_VISUALIZER,
    MERGESORT_VISUALIZER,
};

extern int comparision_count;
