#pragma once
enum screen{
    MAINSCREEN,
    ALGORITHM_LIST,
    DATASTRUCTURE_LIST,
    LINEARSEARCH,
    BINARYSEARCH,
    ARRAY_VISUALIZER,
    QUEUE_VISUALIZER,
    BUBBLESORT_VISUALIZER,
    STACK_VISUALIZER,
};

